## Numpy

Mirar los videos que están en la plataforma de Acámica y tratar de resolver los siguientes ejercicios y preguntas. La documentación de Numpy es muy buena, recomendamos ir familiarizándose con ella.

### Repaso

Importamos la librería

In [2]:
import numpy as np

A partir de una lista podemos crear un arreglo de numpy

In [3]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [4]:
arreglo = np.arange(6)
print(arreglo)

[0 1 2 3 4 5]


Algunas cosas que no se podían hacer con las listas ahora sí se pueden:

1. Sumarle un mismo elemento a toda la lista

In [5]:
arreglo + 1

array([1, 2, 3, 4, 5, 6])

In [5]:
arreglo + 2

array([2, 3, 4, 5, 6, 7])

2. Elevar al cuadrado todos los elementos de una lista

In [6]:
arreglo**2

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [7]:
arreglo**2

array([ 0,  1,  4,  9, 16, 25])

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [8]:
'''
¿Que operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? 
Dar un ejemplo en una celda.
'''
lista = [1,2,3,4,5,6]
arreglo = np.array([1,2,3,4,5,6])

print(len(lista))
print(len(arreglo))

6
6


In [9]:
'''
¿Que operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? 
Explorar algunas opciones y dar un ejemplo en una celda.
'''
lista = [1,2,3,4,5,6]
arreglo = np.array([1,2,3,4,5,6])

print(arreglo.sum())
print(lista.sum())

21


AttributeError: 'list' object has no attribute 'sum'

In [7]:
'''
¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?
'''
print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (1,n)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")


print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto

### EXTRA 1###
'''Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (1,n)
[[1 2 3 4 5 6]] . Shape = (1, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [11]:
arreglo_1 = np.arange(0,10)
print(arreglo_1)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
arreglo_2 = np.linspace(0,9,100)
print(arreglo_2)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son menores que 50.

In [13]:
a = np.arange(0,4)
'''Pista'''
print(a<2)
mask = [True, False, True, False]
print(a[mask])

[ True  True False False]
[0 2]


In [14]:
### RESOLUCION
a = np.arange(10,101)
print(a[a<50])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [17]:
zeros = np.zeros((5,10))
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
zeros[1,:] = 1
zeros[3,:] = 1
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
zeros[:,2] = 2
zeros[:,7] = 2
zeros

array([[0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.]])

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100